version: 2
jobs:
  build:
    working_directory: ~/python-ci
    docker:
      - image: circleci/python:3.6.4

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            sudo pip install -r requirements.txt
      - run:
          command: |
            cd ~/python-ci && nosetests test/math-test.py
      - save_cache:
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

